global:
  grand_tours_db_path: "~/iCloud/Research/Data_Science/Projects/data/grand_tours.db"
  training_db_path: "~/iCloud/Research/Data_Science/Projects/data/training_merged.db"

models:
  linear_regression:
    hyperparameters:
      fit_intercept: true
    param_grid:
  random_forest_regressor:
    hyperparameters:
      min_samples_leaf: 2
      n_estimators: 200
    param_grid:
      min_samples_leaf: [2, 3, 5]
      n_estimators: [300, 400, 600]
  xgboost:
    hyperparameters:
      max_depth: 5
      learning_rate: 0.1
      n_estimators: 300
    param_grid:
      max_depth: [3, 5, 7]
      learning_rate: [0.1, 0.01, 0.001]
      n_estimators: [300, 400, 500]
  linearsvr:
    hyperparameters:
      gamma: 5
    param_grid:
      gamma: [3,5,8]
